remove out-dated swift-version and support macOS
rexmas/JSONValue pull request #29
Opened 2021-03-16 15:57 UTC by haifengkao

2021-03-18 01:54 UTC, rex-remind101 commented on .swift-version
> -5.3.2
this library is intended to be usable in the swift CLI, specifying a `.swift-version` facilitates that. what reason did you remove this?

2021-03-18 02:10 UTC, haifengkao commented on .swift-version
> -5.3.2
<img width="772" alt="截圖 2021-03-18 上午10 09 02" src="https://user-images.githubusercontent.com/4080524/111562975-14fdee80-87d2-11eb-81a2-713d6c3f79a3.png">

2021-03-18 02:11 UTC, haifengkao commented on .swift-version
> -5.3.2
If swift cli needs this file, it's should be preserved, but the podspec needs to specify the swift version as well

2021-03-19 05:18 UTC, rex-remind101 requested changes
.

2021-03-19 05:18 UTC, rex-remind101 commented on .swift-version
> -5.3.2
I found the [link](https://blog.cocoapods.org/CocoaPods-1.7.0-beta/) to the source of what you posted. Thank you for the information. Please restore this file and I will merge the PR.

2021-03-19 05:18 UTC, rex-remind101 commented on .swift-version
> -5.3.2
And publish a new version.

2021-03-19 07:35 UTC, haifengkao commented
I have add it back

2021-03-19 23:28 UTC, merged

2021-04-13 01:52 UTC, rex-remind101 commented
new pod version is published with this change https://cocoapods.org/pods/JSONValueRX